name: Lint GitHub Actions Workflow Configuration

description: A composite action for linting GitHub Actions workflow configuration.

inputs:
  go-version:
    description: The version of Go to use when running `actionslint`.
    default: 1.25.5
    required: false
    type: string

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
      with:
        go-version: ${{ inputs.go-version }}
        cache: false

    - name: Install actionlint
      run: |
        go install github.com/rhysd/actionlint/cmd/actionlint@a443f344ff32813837fa49f7aa6cbc478d770e62 # v1.7.9
      shell: sh

    - name: Lint Workflow Files
      run: |-
        actionlint -color
      shell: sh
