name: Lint GitHub Actions Workflow Configuration

description: A composite action for linting GitHub Actions workflow configuration.

inputs:
  go-version:
    description: The version of Go to use when running `actionslint`.
    default: 1.26.3
    required: false
    type: string

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
      with:
        go-version: ${{ inputs.go-version }}
        cache: false

    - name: Install actionlint
      run: |
        go install github.com/rhysd/actionlint/cmd/actionlint@914e7df21a07ef503a81201c76d2b11c789d3fca # v1.7.12
      shell: sh

    - name: Lint Workflow Files
      run: |-
        actionlint -color
      shell: sh
