name: Lint GitHub Actions Workflow Configuration

description: A composite action for linting GitHub Actions workflow configuration.

inputs:
  go-version:
    description: The version of Go to use when running `actionslint`.
    default: 1.25.5
    required: false
    type: string

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
      with:
        go-version: ${{ inputs.go-version }}

    - name: Install actionlint
      run: |
        go install github.com/rhysd/actionlint/cmd/actionlint@a443f344ff32813837fa49f7aa6cbc478d770e62 # v1.7.9

    - name: Lint Workflow Files
      run: |-
        actionlint -color
